// Generated by Wrangler on Thu May 23 2024 16:46:28 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

export {};
declare global {
	const APP_DEV_KV_NS: KVNamespace;
	const TEST_VARIABLE: "my";
}
