// Generated by Wrangler on Wed May 29 2024 09:51:37 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	APP_PREVIEW_KV_NS: KVNamespace;
	APP_PROD_KV_NS: KVNamespace;
}
